#!/bin/sh

# script/run: Execute the playbook
#
#   Examples: script/run path/to/playbook.yml
#             script/run path/to/playbook.yml -v

set -e

cd "$(dirname "$0")/.."

start=`date +%s` # Start time in seconds
venv="./.venv"

# Fail if the Python virtual environment does not yet exist
if [ ! -d "$venv" ]; then
  echo 'Huh, no virtual environment? Did you run `script/setup` already?'
  exit 2
fi

# Activate the Python virtual environment
. "$venv/bin/activate"

PLAYBOOK_PATH="$(dirname $1)"
PLAYBOOK_NAME="$(basename $1)"
EXTRA_OPTIONS="${2:-}"

pushd ${PLAYBOOK_PATH}
  echo

  # Lint Ansible playbook
  echo "==> Linting playbook…"
  ansible-lint "${PLAYBOOK_NAME}" ${EXTRA_OPTIONS}
  echo "Done."
  echo

  # Run Ansible playbook
  echo "==> Running playbook…"
  ansible-playbook "${PLAYBOOK_NAME}" ${EXTRA_OPTIONS}
  echo "Done."

  echo
popd

end=`date +%s` # End time in seconds
runtime=$((end-start)) # Total elapsed time in seconds
minutes=$((runtime/60)) # Calculate minutes
seconds=$((runtime%60)) # Calculate seconds

echo
echo "==> Total execution time: $minutes minutes and $seconds seconds"
echo
