#!/bin/sh

# script/setup: Set up application for the first time after cloning.

set -e

cd "$(dirname "$0")/.."

if [ ! $(which python) ]; then
  echo "Please install Python (>= 2.7) first"
  exit 2
fi

if [ ! $(which pip) ]; then
  echo "Please install pip first"
  echo
  pip --help
  exit 2
fi

if [ ! $(which virtualenv) ]; then
  echo "==> Installing virtualenv…"
  pip install virtualenv
fi

venv="./.venv"
requirements="./requirements.txt"

# Create Python virtual environment if it does not yet exist
[ -d "$venv" ] || virtualenv "$venv"

# Activate the environment
. "$venv/bin/activate"

# Upgrade to the latest version of pip and install requirement packages
# Hint: Generate package list with 'pip freeze'
echo "==> Installing Requirements…"
pip install --upgrade pip | grep -v 'Requirement already up-to-date'
pip install -r "$requirements" | grep -v 'Requirement already satisfied'
echo "Done."
